### PR TITLE
non turn icons

### PR DESCRIPTION
**Pull request by kepta**
image
This is how the bike looks.

### CODE REVIEW

**Comment by kepta** [comment]
@bhousel review?

**Comment by bhousel** [comment]
These look awesome!

Some thoughts.. 
- would be great if they can fit into 25x25 and still be somewhat pixel aligned
- we don't need to check in .gifs, we'll generate those later

Can you get rid of the .gifs, then merge them in and we'll figure out organization later.

**Comment by kepta** [comment]
@bhousel I changed to view box and tried to pixel align them. 
- My settings had 1 pixel = 1 square grid, each having 8 divisions.
- I tried to set the longest side of icon equal to 23px. This way I ended up having a padding of 1px on both sides of the longest side. Hence, center aligned along the major axis and also center aligned on minor axis.

screen shot 2016-06-20 at 1 51 41 pm
screen shot 2016-06-20 at 1 55 19 pm

What do you say?

**Comment by kepta** [comment]
@bhousel pixel aligned them as much as possible.
Let me know what you think of the tram design and lets merge it, then.

**Comment by bhousel** [comment]
They look great to me, what's the difference between `tram` and `tram_other`?

**Pull request merged**
